apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: backstage
  description: |
    Backstage is an open-source developer portal that puts the developer experience first.
  annotations:
    github.com/project-slug: backstage/backstage
    backstage.io/techdocs-ref: url:https://github.com/backstage/backstage/tree/master
    lighthouse.com/website-url: https://backstage.io
    jenkins.io/github-folder: 'Template%20Repos/CreateTemplateRepo/master'
spec:
  type: library
  owner: CNCF
  lifecycle: experimental
